# Kustomization for the manager deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml

images:
  - name: controller
    newName: ghcr.io/richardmsong/shared-workflows-test
    newTag: latest
